uploads = []
generated = []

[[outputs]]
id = "SguDWUcudRufXcHt9PUr0"
uri = "file://artifacts/dial-in/assets/images/icon.png"
type = "image"
title = "App Icon (1024×1024)"

[[outputs]]
id = "wlLj4yKMpOcDF3QJuXbYM"
uri = "file://artifacts/dial-in/assets/images/splash.png"
type = "image"
title = "Splash Screen (1284×2778)"
