// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/affiliate/AffiliateDashboard.tsx": () => import("../components/mockups/affiliate/AffiliateDashboard.tsx"),
  "./components/mockups/affiliate/InviteCard.tsx": () => import("../components/mockups/affiliate/InviteCard.tsx"),
  "./components/mockups/affiliate/ReferralShare.tsx": () => import("../components/mockups/affiliate/ReferralShare.tsx")
};
